# -*- coding: utf-8 -*-
"""text_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PjPkKfj1Eb4v6gcjWG1kEz-ZuqKwDmr
"""

!pip install transformers

!pip install 'transformers[torch]'

import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

train_data = pd.read_csv('samsum-train.csv')
val_data = pd.read_csv('samsum-validation.csv')

train_data.head()

train_data.shape

# random sampling
train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

train_data.shape

# data pre-processing

import re

def clean_data(text):
  text = re.sub(r'\r\n', ' ', text) # lines
  text = re.sub(r'\s+', ' ', text) # spaces
  text = re.sub(r'<.*?>', ' ', text) # html tags
  text = text.strip().lower()
  return text

train_data['dialogue'] = train_data['dialogue'].apply(clean_data)
train_data['summary'] = train_data['summary'].apply(clean_data)

val_data['dialogue'] = val_data['dialogue'].apply(clean_data)
val_data['summary'] = val_data['summary'].apply(clean_data)

# tokenize
tokenizer = T5Tokenizer.from_pretrained('t5-small')

# raw data => tokenized inputs for fine-tuning

def tokenize(data):
  inputs = tokenizer(data['dialogue'], padding='max_length', max_length=512, truncation=True)
  targets = tokenizer(data['summary'], padding='max_length', max_length=150, truncation=True)

  inputs['labels'] = targets['input_ids'] # token ids => add to input as labels
  return inputs

train_dataset = train_data.apply(tokenize, axis=1).tolist()
val_dataset = val_data.apply(tokenize, axis=1).tolist()

# 1 => EOS & 0 => padding
# attention mask: 1 => valid values & 0 => can be ignored(padding values)

# working with model

model = T5ForConditionalGeneration.from_pretrained('t5-small')

training_args = TrainingArguments(
    output_dir = './results',

    num_train_epochs=6,
    weight_decay=0.01,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    eval_strategy='epoch',
    save_strategy='epoch',

    warmup_steps=500
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

# train the model
trainer.train()

model.save_pretrained('./saved_summary_model')
tokenizer.save_pretrained('./saved_summary_model')

model = T5ForConditionalGeneration.from_pretrained('./saved_summary_model')
tokenizer = T5Tokenizer.from_pretrained('./saved_summary_model')

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

"""test the core logic for summarization"""

def summarize_dialogue(dialogue):
  dialogue = clean_data(dialogue) # clean

  # tokenize
  inputs = tokenizer(
      dialogue,
      padding='max_length',
      max_length=512,
      truncation=True,
      return_tensors='pt'
  ).to(device)

  # generate the summary => token ids
  model.to(device)
  targets = model.generate(
      input_ids=inputs['input_ids'],
      attention_mask=inputs['attention_mask'],
      max_length=150,
      num_beams=4,
      early_stopping=True
  )

  # decoded output
  summary = tokenizer.decode(targets[0], skip_special_tokens=True) # EOS
  return summary

test_dialogue = """
Alice: Hey Rahul, are you free this evening?

Rahul: Yeah, I think so. What's up?

Alice: I was thinking of watching the new movie that came out this week.

Rahul: That sounds fun! What time were you planning to go?

Alice: Around 7 PM. We can grab dinner before the movie.

Rahul: Perfect. Which restaurant do you have in mind?

Alice: There's a new Italian place near the mall that I've been wanting to try.

Rahul: Great choice! I'll meet you there at 6 PM.

Alice: Awesome. See you then!

Rahul: See you! Looking forward to it.
"""

summary = summarize_dialogue(test_dialogue)
print('Summary: ', summary)